trailing_comma = true
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
long_to_short_function_def = true
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = true
format_docstrings = true
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = true
variable_call_indent = []
align_assignment = true
align_struct_field = true
align_conditional = true
align_matrix = true
align_pair_arrow = true
